<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Basic Maps • osmplotr</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">osmplotr</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">Home</a>
</li>
<li>
  <a href="../articles/index.html">Vignettes</a>
</li>
<li>
  <a href="../reference/index.html">Functions</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/ropensci/osmplotr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Basic Maps</h1>
                        <h4 class="author">Mark Padgham</h4>
            
            <h4 class="date">2017-09-19</h4>
          </div>

    
    
<div class="contents">
<p>The <strong>R</strong> package <code>osmplotr</code> uses OpenStreetMap (OSM) data to produce highly customisable maps. Data are downloaded via the <a href="https://cran.r-project.org/package=osmdata"><code>osmdata</code> package</a>, and different aspects of map data - such as roads, buildings, parks, or water bodies - are able to be visually customised. This vignette demonstrates both data downloading and the creation of simple maps. The subsequent vignette (<a href="https://cran.r-project.org/package=osmplotr">‘data-maps’</a>) demonstrates how <code>osmplotr</code> enables user-defined data to be visualised using OSM data. The maps in this vignette represent a small portion of central London, U.K.</p>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>1. Introduction</h1>
<p>A map can be generated using the following simple steps:</p>
<ol style="list-style-type: decimal">
<li>Specify the bounding box for the desired region</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span> (<span class="op">-</span><span class="fl">0.13</span>, <span class="fl">51.51</span>, <span class="op">-</span><span class="fl">0.11</span>, <span class="fl">51.52</span>))</code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Download the desired data—in this case, all building perimeters.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_B &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">bbox =</span> bbox)</code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Initiate an <code>osm_basemap</code> with desired background (<code>bg</code>) colour</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bbox, <span class="dt">bg =</span> <span class="st">'gray20'</span>)</code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Add desired plotting objects in the desired colour.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_B, <span class="dt">col =</span> <span class="st">'gray40'</span>)</code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Print the map</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a1.png">
</div>
<p>The function <code>print_osm_map</code> creates a graphics device that is scaled to the bounding box of the map. Note also that <code>osmplotr</code> maps contain no margins and fill the entire plot area, reflecting the general layout of most printed maps. Additional capabilities of <code>osmplotr</code> are described in the following sections, beginning with downloading and extraction of data.</p>
</div>
<div id="downloading-data" class="section level1">
<h1 class="hasAnchor">
<a href="#downloading-data" class="anchor"></a>2. Downloading Data</h1>
<p>The package <a href="https://cran.r-project.org/package=osmdata"><code>osmdata</code></a> is used to download data from ‘OpenStreetMap’ using the ‘overpass’ API <a href="https://overpass-api.de">overpass API</a>. Data may be returned in either <a href="https://cran.r-project.org/package=sf">‘Simple Features’ (<code>sf</code>)</a> or <a href="https://cran.r-project.org/package=sp">‘R Spatial’ (<code>sp</code>)</a> form. <code>osmplotr</code> has a convenience function, <code>extract_osm_objects</code>, to allow direct import, or the functions of <a href="https://cran.r-project.org/package=osmdata"><code>osmdata</code></a> can also be used directly.</p>
<p>Data of a particular type can be extracted by specifying the appropriate OSM <code>key</code>, as in the above example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span>(<span class="op">-</span><span class="fl">0.13</span>, <span class="fl">51.51</span>, <span class="op">-</span><span class="fl">0.11</span>, <span class="fl">51.52</span>))
dat_B &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">bbox =</span> bbox)
dat_H &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>These objects are of appropriate <code>Spatial</code> classes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span> (dat_B); <span class="kw">class</span> (dat_H)</code></pre></div>
<pre><code>## [1] "sf"         "data.frame"</code></pre>
<pre><code>## [1] "sf"         "data.frame"</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span> (dat_B<span class="op">$</span>geometry); <span class="kw">class</span> (dat_H<span class="op">$</span>geometry)</code></pre></div>
<pre><code>## [1] "sfc_POLYGON" "sfc"</code></pre>
<pre><code>## [1] "sfc_LINESTRING" "sfc"</code></pre>
<p><code>Spatial</code> (<a href="https://cran.r-project.org/package=sf"><code>sp</code></a>) objects may be returned with,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_B &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">bbox =</span> bbox, <span class="dt">sf =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>otherwise <code>sf</code> is used as the default format. The Simple Features (<code>sf</code>) objects with polygons of London buildings and linestrings of highways respectively contain</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nrow</span> (dat_B); <span class="kw">nrow</span> (dat_H)</code></pre></div>
<pre><code>## [1] 1759</code></pre>
<pre><code>## [1] 1133</code></pre>
<p>… 1,759 building polygons and 1,133 highway lines. <code>extract_osm_objects</code> also accepts <code>key-value</code> pairs which are passed to the <a href="https://overpass-api.de">overpass API</a> :</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_T &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'natural'</span>, <span class="dt">value =</span> <span class="st">'tree'</span>, <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>Trees are located by single coordinates and are thus point objects:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span> (dat_T<span class="op">$</span>geometry); <span class="kw">nrow</span> (dat_T)</code></pre></div>
<pre><code>## [1] "sfc_POINT" "sfc"</code></pre>
<pre><code>## [1] 688</code></pre>
<div id="osmdata" class="section level2">
<h2 class="hasAnchor">
<a href="#osmdata" class="anchor"></a>2.1 <code>osmdata</code>
</h2>
<p>The <a href="https://cran.r-project.org/package=osmdata"><code>osmdata</code></a> package provides a more powerful interface for downloading OSM data, and may be used directly with <code>osmplotr</code>. The <code>osmplotr</code> function <code>extract_osm_objects</code> is effectively just a convenience wrapper around <code>omsdata</code> functionality. The primary differences between the two are:</p>
<ol style="list-style-type: decimal">
<li>
<code>osmdata</code> returns <em>all</em> spatial data for a given query; that is, <em>all</em> points, lines, polygons, multilines, and multipolygons, while <code>osmplotr</code> returns a single specified geometric type.</li>
<li>
<code>osmplotr</code> accepts multiple <code>key-value</code> pairs in a single call to <code>extract_osm_objects</code>, which the equivalent <code>osmdata</code> function, <code>add_feature</code>, accepts only a single <code>key-value</code> pair, with queries successively build through multiple calls to <code>add_feature</code>.</li>
</ol>
<p>These differences are illustrated in the following code which generates identical results in both cases (with namespaces explicitly given to aid clarity),</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat1 &lt;-<span class="st"> </span>osmplotr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/osmplotr/topics/extract_osm_objects">extract_osm_objects</a></span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">value =</span> <span class="st">'!primary'</span>,
                                       <span class="dt">bbox =</span> bbox)
dat2 &lt;-<span class="st"> </span>osmdata<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/osmdata/topics/opq">opq</a></span> (<span class="dt">bbox =</span> bbox) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">add_feature</span> (<span class="dt">key =</span> <span class="st">'highway'</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">add_feature</span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">value =</span> <span class="st">'!primary'</span>) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">osmdata_sf</span> ()
dat2 &lt;-<span class="st"> </span>dat2<span class="op">$</span>osm_lines</code></pre></div>
<p>The <code>osmdata</code> function <code><a href="http://www.rdocumentation.org/packages/osmdata/topics/opq">opq()</a></code> constructs an overpass query, with successive calls to <code>add_feature</code> extending the query until it is finally submitted to overpass by <code><a href="http://www.rdocumentation.org/packages/osmdata/topics/osmdata_sf">osmdata_sf()</a></code> (or the <code>sp</code> version <code><a href="http://www.rdocumentation.org/packages/osmdata/topics/osmdata_sp">osmdata_sp()</a></code>).</p>
<p>Note that <code><a href="http://www.rdocumentation.org/packages/osmdata/topics/add_osm_feature">add_feature()</a></code> has to be called twice in this case, because a single call to <code><a href="http://www.rdocumentation.org/packages/osmdata/topics/add_osm_feature">add_feature (key = 'highway', value = '!primary')</a></code> would request <em>all</em> features that are not primary highways. The initial query for <code>key = 'highway'</code> ensures that only npn-primary highways are returned.</p>
</div>
<div id="negation" class="section level2">
<h2 class="hasAnchor">
<a href="#negation" class="anchor"></a>2.2 Negation</h2>
<p>As demonstrated above, negation can be specified by pre-pending <code>!</code> to the <code>value</code> argument so that, for example, all <code>natural</code> objects that are <strong>not</strong> trees can be extracted with</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_NT &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">bbox =</span> bbox, <span class="dt">key =</span> <span class="st">'natural'</span>, <span class="dt">value =</span> <span class="st">'!tree'</span>)</code></pre></div>
<pre><code>## Cannot determine return type; maybe specify explicitly?</code></pre>
<p>The message is generated because of course a request for anything that is not a tree could be for any kind of spatial object. <code>osmplotr</code> makes several educated guesses in the absence of specified return types, but these can always be forced with the <code>return_type</code> parameter:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pts_NT &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">bbox =</span> bbox, <span class="dt">key =</span> <span class="st">'natural'</span>, <span class="dt">value =</span> <span class="st">'!tree'</span>,
                               <span class="dt">return_type =</span> <span class="st">'points'</span>)</code></pre></div>
<p><code>london$dat_H</code> contains all non-primary highways, and was extracted with the call demonstrated above, while <code>london$dat_HP</code> contains the corresponding set of exclusively primary highways. An <code>osmplotr</code> request for <code>key = 'highway'</code> automatically returns line objects (although, again, other kinds of objects may be forced through specifying <code>return_type</code>).</p>
</div>
<div id="additional-key-value-pairs" class="section level2">
<h2 class="hasAnchor">
<a href="#additional-key-value-pairs" class="anchor"></a>2.3 Additional <code>key-value</code> pairs</h2>
<p>Any number of <code>key-value</code> pairs may be passed to <code>extract_osm_objects</code>. For example, a named building can be extracted with</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span>(<span class="op">-</span><span class="fl">0.13</span>, <span class="fl">51.50</span>, <span class="op">-</span><span class="fl">0.11</span>, <span class="fl">51.52</span>))
extra_pairs &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'name'</span>, <span class="st">'Royal.Festival.Hall'</span>)
dat &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">extra_pairs =</span> extra_pairs,
                                       <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>These data are stored in <code>london$dat_RFH</code>. Note that periods or dots are used for white space, and in fact symbolise (in <code>grep</code> terms) any character whatsoever. The polygon of a building at a particular street address can be extracted with</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extra_pairs &lt;-<span class="st"> </span><span class="kw">list</span> (<span class="kw">c</span> (<span class="st">'addr:street'</span>, <span class="st">'Stamford.St'</span>),
                     <span class="kw">c</span> (<span class="st">'addr:housenumber'</span>, <span class="st">'150'</span>))
dat &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">extra_pairs =</span> extra_pairs,
                                      <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>These data are stored as <code>london$dat_ST</code>. Note that addresses generally require combining both <code>addr:street</code> with <code>addr:housenumber</code>.</p>
</div>
<div id="downloading-with-osm_structures-and-make_osm_map" class="section level2">
<h2 class="hasAnchor">
<a href="#downloading-with-osm_structures-and-make_osm_map" class="anchor"></a>2.4 Downloading with <code>osm_structures</code> and <code>make_osm_map</code>
</h2>
<p>The functions <code>osm_structures</code> and <code>make_osm_map</code> aid both downloading multiple OSM data types and plotting (with the latter described below). <code>osm_structures</code> returns a <code>data.frame</code> of OSM structure types, associated <code>key-value</code> pairs, unique suffices which may be appended to data structures for storage purposes, and suggested colours. Passing this list to <code>make_osm_map</code> will return a list of the requested OSM data items, named through combining the <code>dat_prefix</code> specified in <code>make_osm_map</code> and the suffices specified in <code>osm_structures</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">osm_structures</span> ()</code></pre></div>
<pre><code>##     structure      key value suffix      cols
## 1    building building           BU #646464FF
## 2     amenity  amenity            A #787878FF
## 3    waterway waterway            W #646478FF
## 4       grass  landuse grass      G #64A064FF
## 5     natural  natural            N #647864FF
## 6        park  leisure  park      P #647864FF
## 7     highway  highway            H #000000FF
## 8    boundary boundary           BO #C8C8C8FF
## 9        tree  natural  tree      T #64A064FF
## 10 background                          gray20</code></pre>
<p>Many structures are identified by keys only, in which cases the values are empty strings.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">osm_structures</span>()<span class="op">$</span>value [<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]</code></pre></div>
<pre><code>## [1] ""      ""      ""      "grass"</code></pre>
<p>The last row of <code>osm_structures</code> exists only to define the background colour of the map, as explained below (<a href="#4.3%20Automating%20map%20production">4.3 Automating map production</a>).</p>
<p>The suffices include as many letters as are necessary to represent all unique structure names. <code>make_osm_map</code> returns a list of two components:</p>
<ol style="list-style-type: decimal">
<li>
<code>osm_data</code> containing the data objects passed in the <code>osm_structures</code> argument. Any existing <code>osm_data</code> may also be submitted to <code>make_osm_map</code>, in which case any objects not present in the submitted data will be appended to the returned version. If <code>osm_data</code> is not submitted, all objects in <code>osm_structures</code> will be downloaded and returned.</li>
<li>
<code>map</code> containing the <code>ggplot2</code> map objects with layers overlaid according to the sequence and colour schemes specified in <code>osm_structures</code>
</li>
</ol>
<p>The data specified in <code>osm_structures</code> can then be downloaded simply by calling:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">make_osm_map</span> (<span class="dt">structures =</span> <span class="kw">osm_structures</span> (), <span class="dt">bbox =</span> bbox)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span> (dat); <span class="kw">sapply</span> (dat, class); <span class="kw">names</span> (dat<span class="op">$</span>osm_data)</code></pre></div>
<pre><code>## [1] "osm_data" "map"</code></pre>
<pre><code>## $osm_data
## [1] "list"
## 
## $map
## [1] "gg"     "ggplot"</code></pre>
<pre><code>## [1] "dat_BU" "dat_A"  "dat_W"  "dat_G"  "dat_N"  "dat_P"  "dat_H"  "dat_BO"
## [9] "dat_T"</code></pre>
<p>The requested data are contained in <code>dat$osm_data</code>. A list of desired structures can also be passed to this function, for example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">osm_structures</span> (<span class="dt">structures =</span> <span class="kw">c</span>(<span class="st">'building'</span>, <span class="st">'highway'</span>))</code></pre></div>
<pre><code>##    structure      key value suffix      cols
## 1   building building            B #646464FF
## 2    highway  highway            H #000000FF
## 3 background                          gray20</code></pre>
<p>Passing this to <code>make_osm_map</code> will download only these two structures. Finally, note that the example of,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">osm_structures</span> (<span class="dt">structures =</span> <span class="st">'grass'</span>)</code></pre></div>
<pre><code>##    structure     key value suffix      cols
## 1      grass landuse grass      G #64A064FF
## 2 background                         gray20</code></pre>
<p>demonstrates that <code>osm_structures</code> converts a number of common <code>keys</code> to OSM-appropriate <code>key-value</code> pairs.</p>
<div id="the-london-data-of-osmplotr" class="section level3">
<h3 class="hasAnchor">
<a href="#the-london-data-of-osmplotr" class="anchor"></a>2.4.1 The <code>london</code> data of <code>osmplotr</code>
</h3>
<p>To illustrate the use of <code>osm_structures</code> to download data, this section reproduces the code that was used to generate the <code>london</code> data object which forms part of the <code>osmplotr</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">structures &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'highway'</span>, <span class="st">'highway'</span>, <span class="st">'building'</span>, <span class="st">'building'</span>, <span class="st">'building'</span>,
                 <span class="st">'amenity'</span>, <span class="st">'park'</span>, <span class="st">'natural'</span>, <span class="st">'tree'</span>)
structs &lt;-<span class="st"> </span><span class="kw">osm_structures</span> (<span class="dt">structures =</span> structures, <span class="dt">col_scheme =</span> <span class="st">'dark'</span>)
structs<span class="op">$</span>value [<span class="dv">1</span>] &lt;-<span class="st"> '!primary'</span>
structs<span class="op">$</span>value [<span class="dv">2</span>] &lt;-<span class="st"> 'primary'</span>
structs<span class="op">$</span>suffix [<span class="dv">2</span>] &lt;-<span class="st"> 'HP'</span>
structs<span class="op">$</span>value [<span class="dv">3</span>] &lt;-<span class="st"> '!residential'</span>
structs<span class="op">$</span>value [<span class="dv">4</span>] &lt;-<span class="st"> 'residential'</span>
structs<span class="op">$</span>value [<span class="dv">5</span>] &lt;-<span class="st"> 'commercial'</span>
structs<span class="op">$</span>suffix [<span class="dv">3</span>] &lt;-<span class="st"> 'BNR'</span>
structs<span class="op">$</span>suffix [<span class="dv">4</span>] &lt;-<span class="st"> 'BR'</span>
structs<span class="op">$</span>suffix [<span class="dv">5</span>] &lt;-<span class="st"> 'BC'</span></code></pre></div>
<p>Suffices are generated automatically from structure names only, not values, and the suffices for negated forms must therefore be specified manually. The <code>london</code> data can then be downloaded by simply calling <code>make_osm_map</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">london &lt;-<span class="st"> </span><span class="kw">make_osm_map</span> (<span class="dt">structures =</span> structs, <span class="dt">bbox =</span> bbox)<span class="op">$</span>osm_data</code></pre></div>
<p>The requested data are contained in the <code>$osm_data</code> list item. <code>make_osm_map</code> also returns a <code>$map</code> item which is described below (see <a href="#4.3%20make-osm-map">4.3 Automating map production</a>).</p>
</div>
</div>
</div>
<div id="downloading-connected-highways" class="section level1">
<h1 class="hasAnchor">
<a href="#downloading-connected-highways" class="anchor"></a>3. Downloading connected highways</h1>
<p>The visualisation functions described in the second <code>osmplotr</code> vignette (<a href="https://cran.r-project.org/package=osmplotr">Data maps</a>) enable particular regions of maps to be highlighted. While it may often be desirable to highlight regions according to a user’s own data, <code>osmplotr</code> also enables regions to be defined by providing a list of the names of encircling highways. The function which achieves this is <code>connect_highways</code>, which returns a sequential matrix of coordinates from those segments of the named highways which connected continuously and sequentially to form a single enclosed space. An example is,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highways &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'Monmouth.St'</span>, <span class="st">'Short.?s.Gardens'</span>, <span class="st">'Endell.St'</span>, <span class="st">'Long.Acre'</span>,
               <span class="st">'Upper.Saint.Martin'</span>)
highways1 &lt;-<span class="st"> </span><span class="kw">connect_highways</span> (<span class="dt">highways =</span> highways, <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>Note the use of the <a href="https://en.wikipedia.org/wiki/Regular_expression">regex</a> character <code>?</code> which declares that the previous character is optional. This matches both “Shorts Gardens” and “Short’s Gardens”, both of which appear in OSM data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span> (highways1); <span class="kw">length</span> (highways1); highways1 [[<span class="dv">1</span>]] [[<span class="dv">1</span>]]</code></pre></div>
<pre><code>## [1] "list"</code></pre>
<pre><code>## [1] 5</code></pre>
<pre><code>##                   lon      lat
## 1678452807 -0.1270287 51.51370
## 2265298898 -0.1270523 51.51362
## 438170687  -0.1270865 51.51347
## 3192197694 -0.1270902 51.51345
## 9513062    -0.1271692 51.51288</code></pre>
<p>The extraction of bounding polygons from named highways is not fail-safe, and may generate various warning messages. To understand the kinds of conditions under which it may not work, it is useful to examine <code>connect_highways</code> in more detail.</p>
<div id="connect_highways-in-detail" class="section level2">
<h2 class="hasAnchor">
<a href="#connect_highways-in-detail" class="anchor"></a>3.1 <code>connect_highways</code> in detail</h2>
<p><code>connect_highways</code> takes a list of OpenStreetMap highways and sequentially connects closest nodes of adjacent highways until the set of named highways connects to form a cycle. Cases where no circular connection is possible generate an error message. The routine proceeds through the three stages of,</p>
<ol style="list-style-type: decimal">
<li><p>Adding intersection nodes to junctions of ways where these don’t already exist</p></li>
<li><p>Filling a connectivity matrix between the listed highways and extracting the <strong>longest</strong> cycle connecting all of them</p></li>
<li><p>Inserting extra connections between highways until the length of the longest cycle is equal to <code>length (highways)</code>.</p></li>
</ol>
<p>This procedure can not be guaranteed fail-safe owing both to the inherently unpredictable nature of OpenStreetMap, as well as to the unknown relationships between named highways. To enable problematic cases to be examined and hopefully resolved, <code>connect_highways</code> has a <code>plot</code> option:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox_big &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span>(<span class="op">-</span><span class="fl">0.15</span>, <span class="fl">51.5</span>, <span class="op">-</span><span class="fl">0.10</span>, <span class="fl">51.52</span>))
highways &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'Kingsway'</span>, <span class="st">'Holborn'</span>, <span class="st">'Farringdon.St'</span>, <span class="st">'Strand'</span>,
               <span class="st">'Fleet.St'</span>, <span class="st">'Aldwych'</span>)
highway_list &lt;-<span class="st"> </span><span class="kw">connect_highways</span> (<span class="dt">highways =</span> highways, <span class="dt">bbox =</span> bbox_big,
                                  <span class="dt">plot =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Warning: Cycle unable to be extended through all ways</code></pre>
<p><img src="basic-maps_files/figure-html/connect-highways-manual-plot-1.png" width="384"></p>
<p>The plot depicts each highway in a different colour, along with numbers at start and end points of each segment. This plot reveals in this case that highway#6 (‘Aldwych’) is actually nested within two components of highway#4 (‘Strand’). <code>connect_highways</code> searches for the shortest path connecting all named highways, and since ‘Strand’ connects to both highways#1 and #5, the shortest path excludes #6. This exclusion of one of the named components generates the warning message.</p>
<p>These connected polygons returned from <code>connect_highways</code> can then be used to highlight the enclosed regions within maps, as demonstrated in the second vignette, <a href="https://cran.r-project.org/package=osmplotr">‘Data Maps’</a>.</p>
</div>
</div>
<div id="producing-maps" class="section level1">
<h1 class="hasAnchor">
<a href="#producing-maps" class="anchor"></a>4. Producing maps</h1>
<p>Maps will generally contain multiple kinds of OSM data, for example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_B &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'building'</span>, <span class="dt">bbox =</span> bbox)
dat_H &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">bbox =</span> bbox)
dat_T &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'natural'</span>, <span class="dt">value =</span> <span class="st">'tree'</span>, <span class="dt">bbox =</span> bbox)</code></pre></div>
<p>As illustrated above, plotting maps requires first making a basemap with a specified background colour. Portions of maps can also be plotted by creating a <code>basemap</code> with a smaller bounding box.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox_small &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span>(<span class="op">-</span><span class="fl">0.13</span>, <span class="fl">51.51</span>, <span class="op">-</span><span class="fl">0.11</span>, <span class="fl">51.52</span>))
map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bbox_small, <span class="dt">bg =</span> <span class="st">'gray20'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_H, <span class="dt">col =</span> <span class="st">'gray70'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_B, <span class="dt">col =</span> <span class="st">'gray40'</span>)</code></pre></div>
<p><code>map</code> is then a <code>ggplot2</code> which may be viewed simply by passing it to <code>print_osm_map</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a2.png">
</div>
<p>Other graphical parameters can also be passed to <code>add_osm_objects</code>, such as border colours or line widths and types. For example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bbox_small, <span class="dt">bg =</span> <span class="st">'gray20'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_B, <span class="dt">col =</span> <span class="st">'gray40'</span>, <span class="dt">border =</span> <span class="st">'orange'</span>,
                        <span class="dt">size =</span> <span class="fl">0.2</span>)
<span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a3.png">
</div>
<p>The <code>size</code> argument is passed to the corresponding <code>ggplot2</code> routine for plotting polygons, lines, or points, and respectively determines widths of lines (for polygon outlines and for lines), and sizes of points. The <code>col</code> argument determines the fill colour of polygons, or the colour of lines or points.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_H, <span class="dt">col =</span> <span class="st">'gray70'</span>, <span class="dt">size =</span> <span class="fl">0.7</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_T, <span class="dt">col =</span> <span class="st">'green'</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">1</span>)
<span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a4.png">
</div>
<p>Note also that the <code>shape</code> parameter determines the point shape, for details of which see <code><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes_linetype_size_shape">?ggplot2::shape</a></code>. Also note that plot order affects the final outcome, because components are sequentially overlaid and thus the same map components plotted in a different order will generally produce a different result.</p>
<div id="saving-maps" class="section level2">
<h2 class="hasAnchor">
<a href="#saving-maps" class="anchor"></a>4.1 Saving Maps</h2>
<p>The function <code>print_osm_map()</code> can be used to print either to on-screen graphical devices or to graphics files (see, for example, <code>?png</code> for a list of possible graphics devices). Sizes and resolutions of devices may be specified with the appropriate parameters. Device dimensions are scaled by default to the proportions of the bounding box (although this can be over-ridden).</p>
<p>A screen-based device simply requires</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print_osm_map</span> (map)</code></pre></div>
<p>while examples of writing higher resolution versions to files include:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print_osm_map</span> (map, <span class="dt">filename =</span> <span class="st">"map.png"</span>, <span class="dt">width =</span> <span class="dv">10</span>,
               <span class="dt">units =</span> <span class="st">"in"</span>, <span class="dt">dpi =</span> map_dpi)
<span class="kw">print_osm_map</span> (map, <span class="dt">filename =</span> <span class="st">"map.eps"</span>, <span class="dt">width =</span> <span class="dv">1000</span>,
               <span class="dt">units =</span> <span class="st">"px"</span>, <span class="dt">dpi =</span> map_dpi)
<span class="kw">print_osm_map</span> (map, <span class="dt">filename =</span> <span class="st">"map"</span>, <span class="dt">device =</span> <span class="st">"jpeg"</span>, <span class="dt">width =</span> <span class="dv">10</span>, <span class="dt">units =</span> <span class="st">"cm"</span>)</code></pre></div>
</div>
<div id="plotting-different-osm-structures" class="section level2">
<h2 class="hasAnchor">
<a href="#plotting-different-osm-structures" class="anchor"></a>4.2 Plotting different OSM Structures</h2>
<p>The ability demonstrated above to use negation in <code>extract-osm-objects</code> allows different kinds of the same object to be visually contrasted, for example primary and non-primary highways:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat_HP &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">value =</span> <span class="st">'primary'</span>, <span class="dt">bbox =</span> bbox)
dat_H &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">key =</span> <span class="st">'highway'</span>, <span class="dt">value =</span> <span class="st">'!primary'</span>, <span class="dt">bbox =</span> bbox)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bbox_small, <span class="dt">bg =</span> <span class="st">'gray20'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_H, <span class="dt">col =</span> <span class="st">'gray50'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_HP, <span class="dt">col =</span> <span class="st">'gray80'</span>, <span class="dt">size =</span> <span class="dv">2</span>)
<span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a5.png">
</div>
<p>The additional <code>key-value</code> pairs demonstrated above (for Royal Festival Hall, <code>dat_RFH</code> and 150 Stamford Street, <code>dat_ST</code>) also demonstrated above allow for highly customised maps in which distinct objects are plotting with different colour schemes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bbox_small2 &lt;-<span class="st"> </span><span class="kw">get_bbox</span> (<span class="kw">c</span> (<span class="op">-</span><span class="fl">0.118</span>, <span class="fl">51.504</span>, <span class="op">-</span><span class="fl">0.110</span>, <span class="fl">51.507</span>))
map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bbox_small2, <span class="dt">bg =</span> <span class="st">'gray95'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_H, <span class="dt">col =</span> <span class="st">'gray80'</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_HP, <span class="dt">col =</span> <span class="st">'gray20'</span>, <span class="dt">size =</span> <span class="dv">2</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_RFH, <span class="dt">col =</span> <span class="st">'orange'</span>, <span class="dt">border =</span> <span class="st">'red'</span>, <span class="dt">size =</span> <span class="dv">2</span>)
map &lt;-<span class="st"> </span><span class="kw">add_osm_objects</span> (map, dat_ST, <span class="dt">col =</span> <span class="st">'skyblue'</span>, <span class="dt">border =</span> <span class="st">'blue'</span>, <span class="dt">size =</span> <span class="dv">2</span>)
<span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a7.png">
</div>
</div>
<div id="filling-within-boundary-lines" class="section level2">
<h2 class="hasAnchor">
<a href="#filling-within-boundary-lines" class="anchor"></a>4.3 Filling within boundary lines</h2>
<p>Different portions of a map may sometimes be delineated by lines, for example with coastlines which are always represented in OpenStreetMap as lines. Plotting the water or land either side of a coastline in a single block of colour requires the regions to be polygons, not lines. <code>osmplotr</code> has a function <code>osm_line2poly()</code> which converts boundary lines extending beyond a given bounding box into polygons encircling the perimeter of the bounding box. An example is given in <code>?osm_line2poly</code>, using both the <code>osmdata</code> package to obtain the bounding box of a named region, and the <code>magrittr</code> pipe operator.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span> (osmdata)
bb &lt;-<span class="st"> </span>osmdata<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/osmdata/topics/getbb">getbb</a></span> (<span class="st">"melbourne, australia"</span>)
coast &lt;-<span class="st"> </span><span class="kw">extract_osm_objects</span> (<span class="dt">bbox =</span> bb, <span class="dt">key =</span> <span class="st">"natural"</span>, <span class="dt">value =</span> <span class="st">"coastline"</span>,
                              <span class="dt">return_type =</span> <span class="st">"line"</span>)
coast &lt;-<span class="st"> </span><span class="kw">osm_line2poly</span> (coast, <span class="dt">bbox =</span> bb)
map &lt;-<span class="st"> </span><span class="kw">osm_basemap</span> (<span class="dt">bbox =</span> bb) <span class="op">%&gt;%</span>
<span class="st">        </span><span class="kw">add_osm_objects</span> (coast [[<span class="dv">1</span>]], <span class="dt">col =</span> <span class="st">"lightsteelblue"</span>) <span class="op">%&gt;%</span>
<span class="st">        </span><span class="kw">print_osm_map</span> ()</code></pre></div>
<p>The <code>osm_line2poly()</code> function returns a list of two <code>sf</code> polygons. For coastline, one of these will correspond to water, one to land. In the preceding example, the first polygon is the ocean, which is coloured in <code>"lightsteelblue"</code>. Users must determine for themselves which polygon is to be plotted in which colour. Note that <code>osm_line2poly()</code> only accepts <code>sf</code>-formatted data, and not <code>sp</code>.</p>
</div>
<div id="automating-map-production" class="section level2">
<h2 class="hasAnchor">
<a href="#automating-map-production" class="anchor"></a>4.4 Automating map production</h2>
<p>As indicated above (<a href="#2.4%20downloading2">2.4 Downloading with <code>osm_structures</code> and <code>make_osm_map</code></a>), the production of maps overlaying various type of OSM objects is facilitated with <code>make_osm_map</code>. The structure of a map is defined by <code>osm_structures</code> as described above.</p>
<p>Producing a map with customised data is as simple as,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">structs &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'highway'</span>, <span class="st">'building'</span>, <span class="st">'park'</span>, <span class="st">'tree'</span>)
structures &lt;-<span class="st"> </span><span class="kw">osm_structures</span> (<span class="dt">structures =</span> structs, <span class="dt">col_scheme =</span> <span class="st">'light'</span>)
dat &lt;-<span class="st"> </span><span class="kw">make_osm_map</span> (<span class="dt">structures =</span> structures, <span class="dt">bbox =</span> bbox_small)
<span class="kw">print_osm_map</span> (dat<span class="op">$</span>map)</code></pre></div>
<div class="figure">
<img src="map_a8.png">
</div>
<p>Calling <code>make_osm_map()</code> downloads the requested structures within the given <code>bbox</code> and returns a list of two components, the first of which contains the downloaded data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span> (dat); <span class="kw">names</span> (dat<span class="op">$</span>osm_data)</code></pre></div>
<pre><code>## [1] "osm_data" "map"</code></pre>
<pre><code>## [1] "dat_B" "dat_H" "dat_P" "dat_A" "dat_P" "dat_T"</code></pre>
<p>Pre-downloaded data may also be passed to <code>make_osm_map()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">make_osm_map</span> (<span class="dt">structures =</span> structures, <span class="dt">osm_data =</span> dat<span class="op">$</span>osm_data,
                     <span class="dt">bbox =</span> bbox)
<span class="kw">print_osm_map</span> (dat<span class="op">$</span>map)</code></pre></div>
<div class="figure">
<img src="map_a9.png">
</div>
<p>Note that omitting the bounding box argument (<code>bbox</code>) produces a map with a bounding box is extracted as the <strong>largest</strong> box spanning all objects in <code>osm_data</code>. This may be considerably larger than the desired boundaries, particularly because highways are returned by <code>overpass</code> in their entirety, and will generally extend well beyond the specified bounding box.</p>
<p>Finally, objects in maps are overlaid on the plot according to the order of rows in <code>osm_structures</code>, with the single exception that <code>background</code> is plotted first. This order can be readily changed or restricted simply by submitting structures in a desired order.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">structs &lt;-<span class="st"> </span><span class="kw">c</span> (<span class="st">'amenity'</span>, <span class="st">'building'</span>, <span class="st">'highway'</span>, <span class="st">'park'</span>)
<span class="kw">osm_structures</span> (structs, <span class="dt">col_scheme =</span> <span class="st">'light'</span>)</code></pre></div>
<pre><code>##    structure      key value suffix      cols
## 1    amenity  amenity            A #DCDCDCFF
## 2   building building            B #C8C8C8FF
## 3    highway  highway            H #969696FF
## 4       park  leisure  park      P #C8DCC8FF
## 5 background                          gray95</code></pre>
</div>
<div id="axes" class="section level2">
<h2 class="hasAnchor">
<a href="#axes" class="anchor"></a>4.5 Axes</h2>
<p>Axes may be added to maps using the <code>add_axes</code> function. In contrast to many <code>R</code> packages for producing maps, maps in <code>osmplotr</code> fill the entire plotting space, and axes are added <em>internal</em> to this space. The separate function for adding axes allows them to be overlaid on top of all previous layers.</p>
<p>Axes added to a dark version of the previous map look like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">structures &lt;-<span class="st"> </span><span class="kw">osm_structures</span> (<span class="dt">structures =</span> structs, <span class="dt">col_scheme =</span> <span class="st">'dark'</span>)
dat &lt;-<span class="st"> </span><span class="kw">make_osm_map</span> (<span class="dt">structures =</span> structures, <span class="dt">osm_data =</span> dat<span class="op">$</span>osm_dat,
                     <span class="dt">bbox =</span> bbox_small)
map &lt;-<span class="st"> </span><span class="kw">add_axes</span> (dat<span class="op">$</span>map, <span class="dt">colour =</span> <span class="st">'black'</span>)</code></pre></div>
<p>Note that, as described above, <code>make_osm_map</code> returns a list of two items: (i) potentially modified data (in <code>$osm_data</code>) and (ii) the map object (in <code>$map</code>). All other <code>add_</code> functions take a map object as one argument and return the single value of the modified map object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a10.png">
</div>
<p>This map reveals that the axes and labels are printed above semi-transparent background rectangles, with transparency controlled by the <code>alpha</code> parameter. Axes are always plotted on the left and lower side, but positions can be adjusted with the <code>pos</code> parameter which specifies the positions of axes and labels relative to entire plot device</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">map &lt;-<span class="st"> </span><span class="kw">add_axes</span> (map, <span class="dt">colour =</span> <span class="st">'blue'</span>, <span class="dt">pos =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.2</span>),
                      <span class="dt">fontsize =</span> <span class="dv">5</span>, <span class="dt">fontface =</span> <span class="dv">3</span>, <span class="dt">fontfamily =</span> <span class="st">"Times"</span>)
<span class="kw">print_osm_map</span> (map)</code></pre></div>
<div class="figure">
<img src="map_a11.png">
</div>
<p>The second call to <code>add_axes</code> overlaid additional axes on a map that already had axes from the previous call. This call also demonstrates how sizes and other font characteristics of text labels can be specified.</p>
<p>Finally, the current version of <code>osmplotr</code> does not allow text labels of axes to be rotated. (This is because the semi-transparent underlays are generated with <code><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_text">ggplot2::geom_label</a></code> which currently prevents rotation.)</p>
<p>Click on the following link to proceed to the second <code>osmplotr</code> vignette: <a href="https://cran.r-project.org/package=osmplotr">Data maps</a></p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">1. Introduction</a></li>
      <li>
<a href="#downloading-data">2. Downloading Data</a><ul class="nav nav-pills nav-stacked">
<li><a href="#osmdata">2.1 <code>osmdata</code></a></li>
      <li><a href="#negation">2.2 Negation</a></li>
      <li><a href="#additional-key-value-pairs">2.3 Additional <code>key-value</code> pairs</a></li>
      <li><a href="#downloading-with-osm_structures-and-make_osm_map">2.4 Downloading with <code>osm_structures</code> and <code>make_osm_map</code></a></li>
      </ul>
</li>
      <li>
<a href="#downloading-connected-highways">3. Downloading connected highways</a><ul class="nav nav-pills nav-stacked">
<li><a href="#connect_highways-in-detail">3.1 <code>connect_highways</code> in detail</a></li>
      </ul>
</li>
      <li>
<a href="#producing-maps">4. Producing maps</a><ul class="nav nav-pills nav-stacked">
<li><a href="#saving-maps">4.1 Saving Maps</a></li>
      <li><a href="#plotting-different-osm-structures">4.2 Plotting different OSM Structures</a></li>
      <li><a href="#filling-within-boundary-lines">4.3 Filling within boundary lines</a></li>
      <li><a href="#automating-map-production">4.4 Automating map production</a></li>
      <li><a href="#axes">4.5 Axes</a></li>
      </ul>
</li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Mark Padgham.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
