#' add.osm.lines
#'
#' plot.osm.polygons initiates a graphics device to which add.osm.lines () and
#' add.osm.polygons () adds successive layers of lines and polygons generated by
#' get.osm.polygons ().
#'
#' @param lines = a list of lines returned by get.osm.polygons
#' @param col = colour of lines (default = "gray40")
#' @return nothing (adds to graphics.device opened with plot.osm.polygons)

add.lines <- function (lines=lines, col="gray40")
{
  plotfun <- function (i) 
  {
    xy <- slot (slot (i, "Lines") [[1]], "coords")
    lines (xy, col=col)
  }
  junk <- lapply (slot (lines, "lines"), plotfun)
}

