#' add.osm.polygons
#'
#' plot.osm.polygons initiates a graphics device to which add.osm.polygons ()
#' adds successive layers of polygons generated by get.osm.polygons ().
#'
#' @param poly = a list of polygons returned by get.osm.polygons
#' @param col = colour of polygons (default = "gray40")
#' @return nothing (adds to graphics.device opened with plot.osm.polygons)

add.osm.polygons <- function (poly=poly, col="gray40")
{
    plotfun <- function (i) 
    {
        xy <- slot (slot (i, "Polygons") [[1]], "coords")
        polypath (xy, border=NA, col=col)
    }
    junk <- lapply (slot (poly, "polygons"), plotfun)
}

